image: "rust:alpine"

stages:
  - test
  - build
  - bench

default:
  before_script:
    - apk add build-base

tests:
  stage: test
  script:
  - rustc --version && cargo --version      # Print version info for debugging
  - sleep 10000
  - cargo test --all --verbose

release_build:
  stage: build
  script:
  - cargo build --release
  - mv target/release/strace-parser .
  - strip strace-parser
  - sha256sum strace-parser | tee sha.txt
  artifacts:
    paths:
    - strace-parser
    - sha.txt
  only:
    refs:
      - master
      - tags

benches:
  stage: bench
  script:
    - cargo bench
  only:
    variables:
      - $BENCH
