image: "rust:alpine"

stages:
  - test
  - build

tests:
  stage: test
  script:
  - apk add build-base
  - rustc --version && cargo --version      # Print version info for debugging
  - cargo test --all --verbose
  - cargo bench

release_build:
  stage: build
  script:
  - cargo build --release
  - mv target/release/strace-parser .
  - strip strace-parser
  - sha256sum strace-parser | tee sha.txt
  artifacts:
    paths:
    - strace-parser
    - sha.txt
  only:
    refs:
      - master
      - tags
