[package]
name = "strace-parser"
version = "0.5.0"
authors = ["Will Chandler <wchandler@gitlab.com>"]
edition = "2018"

[dependencies]
chrono = "0.4"
clap = "2.32.0"
memmap = "0.7"
strace-parse = { path = "strace-parse" }

[dev-dependencies]
criterion = "0.2"
rayon = "1.0"

[workspace]

[[bench]]
name = "strace_parse"
harness = false

[profile.release]
lto = true
incremental = false
codegen-units = 1
panic = "abort"

[features]
nightly = []
