[package]
name = "strace-parser"
version = "0.3.7"
authors = ["Will Chandler <wchandler@gitlab.com>"]
edition = "2018"

[dependencies]
chrono = "0.4"
clap = "2.32.0"
fxhash = "0.2.1"
lazy_static = "1.2.0"
petgraph = "0.4.13"
rayon = "1.0"
rayon-hash = "0.4.1"

[dev-dependencies]
criterion = "0.2"

[[bench]]
name = "strace_parse"
harness = false

[profile.release]
lto = true
incremental = false
codegen-units = 1
panic = "abort"

[features]
nightly = []
