[package]
name = "strace-parser"
version = "0.2.2"
authors = ["Will Chandler <wchandler@gitlab.com>"]
edition = "2018"

[dependencies]
chrono = "0.4"
clap = "2.32.0"
petgraph = "0.4.13"
rayon = "1.0"
smallvec = "0.6.5"

[dev-dependencies]
criterion = "0.2"

[[bench]]
name = "strace_parse"
harness = false
