[package]
name = "strace-parse"
version = "0.5.2"
authors = ["Will Chandler <wchandler@gitlab.com>"]
edition = "2018"

[dependencies]
chrono = "0.4.9"
hashbrown = { version = "0.6.0", features = ["rayon"] }
lazy_static = "1.4.0"
petgraph = "0.4.13"
rayon = "1.2.0"
