[package]
name = "strace-parse"
version = "0.5.1"
authors = ["Will Chandler <wchandler@gitlab.com>"]
edition = "2018"

[dependencies]
chrono = "0.4"
hashbrown = { version = "0.5", features = ["rayon"] }
lazy_static = "1.3.0"
petgraph = "0.4.13"
rayon = "1.1"
