[package]
name = "strace-parse"
version = "0.5.2"
authors = ["Will Chandler <wchandler@gitlab.com>"]
edition = "2018"

[dependencies]
chrono = "0.4.11"
lazy_static = "1.4.0"
petgraph = "0.5.0"
rayon = "1.3.0"
