[package]
name = "parser"
version = "0.6.0"
authors = ["Will Chandler <wchandler@gitlab.com>"]
edition = "2018"

[dependencies]
chrono = "0.4.11"
lazy_static = "1.4.0"
petgraph = "0.5.1"
rayon = "1.3.1"
